name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    # - uses: actions/checkout@v3
    # - name: Build the Docker image
    #   run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
    
    - name: Checkout
      uses: actions/checkout@v4
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    - name: Build and export
      uses: docker/build-push-action@v5
      with:
        context: .
        tags: qca:$(date +%s)
        outputs: type=docker,dest=/tmp/qca-image.tar
    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: qca-image
        path: /tmp/qca-image.tar

      
  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download QCA image artifact
        uses: actions/download-artifact@v3
        with:
          name: qca-image
          path: /tmp
      - name: Load image
        run: |
          docker load --input /tmp/qca-image.tar
          docker image ls -a
      - name: Test with pytest
        run: |
          docker run qca pytest
